name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # 1. Instalamos y construimos DENTRO de la carpeta del proyecto
      - name: Install and Build
        run: |
          cd modern_art_gallery
          npm install
          npm run build
          
      - uses: actions/configure-pages@v4
      
      # 2. Subimos la carpeta dist que está DENTRO de modern_art_gallery
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './modern_art_gallery/dist'
          
      - uses: actions/deploy-pages@v4